### PR TITLE
correct paren in wrong place

### PR DESCRIPTION
**Pull request by mpmeyer**
I believe the parenthesis in the return statement is in the wrong place, resulting in the return of the response object instead of performing the redirect.

### CODE REVIEW

**Comment by mpmeyer** [comment]
What I am seeing is that after login to my CAS server instead of redirecting back to my originating url, I get the response rendered into my browser.

The code after the recent bug fix:
https://github.com/jsumners/hapi-cas/commit/6ae8d2e480c6ee2204cfc4f50863afbf395bf7fe#diff-18e559ebd3cc204a52bc1dc3db2adf8bL106

has the side effect of returning the response object and not actually performing the redirect.

**Comment by jsumners** [comment]
And that issue is resolved with this change?

**Comment by mpmeyer** [comment]
Yes, after the service validate, the redirect is now happening and is returning to my originating page.

**Comment by jsumners** [comment]
Please change the destination branch for the merge to the `develop` branch.

**Pull request closed without merging**
